# Generated by Django 4.0.1 on 2022-04-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmsp', '0004_remove_stock_product_alter_product_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sales',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmsp.product'),
        ),
    ]
