# Generated by Django 4.0.1 on 2022-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmsp', '0005_rename_total_price_sales_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='now',
            field=models.BooleanField(default=True),
        ),
    ]
