# Generated by Django 4.0.1 on 2022-04-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmsp', '0007_rename_price_sales_grand_total_remove_sales_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='sales_id',
            new_name='sales',
        ),
    ]
